version: '3.8'

services:
  slack-to-dingtalk:
    build: .
    container_name: slack-to-dingtalk
    environment:
      - DINGTALK_WEBHOOK=https://oapi.dingtalk.com/robot/send?access_token=
    ports:
      - "3000:3000"
    restart: unless-stopped
