version: '3.8'

services:
  slack-to-dingtalk:
    build: .
    container_name: slack-to-dingtalk
    environment:
      - DINGTALK_WEBHOOK=https://oapi.dingtalk.com/robot/send?access_token=
      - PORT=3099
    ports:
      - "3099:3099"
    restart: unless-stopped
